# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bb823ae575348c91fbc5e73e71ee42dc2efa73605a77500fdcd23e381a42c8ed3ee402947c112e9142461c844f8ad3571b4018cd20513117439bbb3df159c938

test:
  secret_key_base: 69a8996cfd4c36002cebdc2d7690df9cadc11a2853e1349dfe73373c15fc36d48265c992436205016cc9f95e118ba9cce4693ee38af0639efcfe3570e268c61d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
